### Collection of list of events booked by user
POST http://localhost:3000/
Content-Type: application/json
X-REQUEST-TYPE: GraphQL
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjcsImVtYWlsIjoiU29meWFubkFnYWluQG9jbG9jay5jb20iLCJmaXJzdG5hbWUiOiJMZSBTIiwibGFzdG5hbWUiOiJIZWxwZXIiLCJpYXQiOjE2OTA1NTIwMDAsImV4cCI6MTY5MzE0NDAwMH0.ebs8RoYHO6SYJqplZ0XKMjMqamnkuM1kKoP7YAN5YfI

query BookEvents {
  bookevents {
    favorite
    comment
    user_id
    event_id
  }
}