### Collection of events list
POST http://localhost:3000/
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query Events {
  events {
    id
    day
    description
    slot
  }
}

### Collection of one event
POST http://localhost:3000/
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query oneEvent ($eventId: Int!) {
  event(id: $eventId) {
    day
    description
    id
    slot
  }
}

{
  "eventId": 53
}

### Creation of an event
POST http://localhost:3000/
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation AddEvent($input: EventAddInput!) {
  addEvent(input: $input) {
    id
    day
    description
    slot
  }
}

{
  "input": {
    "description": "Dummy event 1",
    "slot": "08:00-10:00",
    "day": "04/08/24",
    "game_id": 3,
    "site_id": 2
  }
}

### Update of an event
POST http://localhost:3000/
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation UpdateEvent($updateEventId: Int!, $input: EventUpdateInput!) {
  updateEvent(id: $updateEventId, input: $input) {
    id
    day
    description
    slot
  }
}

{
  "updateEventId": 54,
  "input": {
    "description": "update 2"
  }
}

### Delete of an event
POST http://localhost:3000/
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation DeleteEvent($deleteEventId: Int!) {
  deleteEvent(id: $deleteEventId)
}

{
  "deleteEventId": 53
}

### Register
POST http://localhost:3000/
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation RegisterUser($input: UserRegisterInput!) {
  registerUser(input: $input) {
    email
    firstname
  }
}

{
  "input": {
    "email": "sofyann@oclock.io",
    "password": "superpass",
    "firstname": "sofyann",
    "lastname": "Helper"
  }
}


### Login
POST http://localhost:3000/
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query ($email: String!, $password: String!){
  login(email: $email, password: $password){
    token
  }
}

{
  "email": "sofyann@oclock.io",
  "password": "superpass"
}

### Collection of User info
POST http://localhost:3000/
Content-Type: application/json
X-REQUEST-TYPE: GraphQL
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTgsImVtYWlsIjoic29meWFubkBvY2xvY2suaW8iLCJmaXJzdG5hbWUiOiJzb2Z5YW5uIiwibGFzdG5hbWUiOiJIZWxwZXIiLCJpcCI6Ijo6ZmZmZjoxMjcuMC4wLjEiLCJpYXQiOjE2OTAzODExMTEsImV4cCI6MTY5Mjk3MzExMX0.9zEbXokLntC_cAKidxaDIaUN_GyPiL1lpMur1TPaaMw

query {
  user {
    id
    email
    firstname
    lastname
  }
}

### Update of a User
POST http://localhost:3000/
Content-Type: application/json
X-REQUEST-TYPE: GraphQL
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTgsImVtYWlsIjoic29meWFubkBvY2xvY2suaW8iLCJmaXJzdG5hbWUiOiJzb2Z5YW5uIiwibGFzdG5hbWUiOiJIZWxwZXIiLCJpcCI6Ijo6ZmZmZjoxMjcuMC4wLjEiLCJpYXQiOjE2OTAzODExMTEsImV4cCI6MTY5Mjk3MzExMX0.9zEbXokLntC_cAKidxaDIaUN_GyPiL1lpMur1TPaaMw

mutation Mutation($updateUserId: Int!, $input: UserUpdateInput!) {
  updateUser(id: $updateUserId, input: $input) {
    id
    email
    firstname
    lastname
  }
}

{
  "input": {
    "lastname": "Le S"
  }
}


