### Register
POST http://localhost:3000/
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation RegisterUser($input: UserRegisterInput!) {
  registerUser(input: $input) {
    email
    firstname
  }
}

{
  "input": {
    "email": "sofyannTestFavorite@oclock.io",
    "password": "superpass",
    "firstname": "Sofyann",
    "lastname": "Le S"
  }
}

### Login
POST http://localhost:3000/
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query ($email: String!, $password: String!){
  login(email: $email, password: $password){
    token
  }
}

{
  "email": "sofyannTestFavorite@oclock.io",
  "password": "superpass"
}

### Collection of User info
POST http://localhost:3000/
Content-Type: application/json
X-REQUEST-TYPE: GraphQL
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzMsImVtYWlsIjoic29meWFublRlc3RGYXZvcml0ZUBvY2xvY2suaW8iLCJmaXJzdG5hbWUiOiJTb2Z5YW5uIiwibGFzdG5hbWUiOiJMZSBTIiwiaWF0IjoxNjkwNTM0MjUwLCJleHAiOjE2OTMxMjYyNTB9.Ds7CTe3QTHWQ7x-RgKceYtM6GUGjfbjAnEPFhmqRmkY

query {
  user {
    id
    email
    firstname
    lastname
  }
}

### Update of a User info
POST http://localhost:3000/
Content-Type: application/json
X-REQUEST-TYPE: GraphQL
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzMsImVtYWlsIjoic29meWFublRlc3RGYXZvcml0ZUBvY2xvY2suaW8iLCJmaXJzdG5hbWUiOiJTb2Z5YW5uIiwibGFzdG5hbWUiOiJMZSBTIiwiaWF0IjoxNjkwNTM0MjUwLCJleHAiOjE2OTMxMjYyNTB9.Ds7CTe3QTHWQ7x-RgKceYtM6GUGjfbjAnEPFhmqRmkY

mutation UpdateUser($input: UserUpdateInput!) {
  updateUser(input: $input) {
    id
    email
    password
    firstname
    lastname
  }
}

{
  "input": {
    "lastname": "Another S"
  }
}

### Delete of User
POST http://localhost:3000/
Content-Type: application/json
X-REQUEST-TYPE: GraphQL
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzMsImVtYWlsIjoic29meWFublRlc3RGYXZvcml0ZUBvY2xvY2suaW8iLCJmaXJzdG5hbWUiOiJTb2Z5YW5uIiwibGFzdG5hbWUiOiJMZSBTIiwiaWF0IjoxNjkwNTM0MjUwLCJleHAiOjE2OTMxMjYyNTB9.Ds7CTe3QTHWQ7x-RgKceYtM6GUGjfbjAnEPFhmqRmkY

mutation Delete {
  deleteUser
}

### Collection of list of events booked by user
POST http://localhost:3000/
Content-Type: application/json
X-REQUEST-TYPE: GraphQL
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzMsImVtYWlsIjoic29meWFublRlc3RGYXZvcml0ZUBvY2xvY2suaW8iLCJmaXJzdG5hbWUiOiJTb2Z5YW5uIiwibGFzdG5hbWUiOiJMZSBTIiwiaWF0IjoxNjkwNTM0MjUwLCJleHAiOjE2OTMxMjYyNTB9.Ds7CTe3QTHWQ7x-RgKceYtM6GUGjfbjAnEPFhmqRmkY

query User {
  user {
    id
    email
    firstname
    lastname
    events {
      id
      day
      description
      slot
    }
  }
}

### Query to book an event 
POST http://localhost:3000/
Content-Type: application/json
X-REQUEST-TYPE: GraphQL
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzMsImVtYWlsIjoic29meWFublRlc3RGYXZvcml0ZUBvY2xvY2suaW8iLCJmaXJzdG5hbWUiOiJTb2Z5YW5uIiwibGFzdG5hbWUiOiJMZSBTIiwiaWF0IjoxNjkwNTM0MjUwLCJleHAiOjE2OTMxMjYyNTB9.Ds7CTe3QTHWQ7x-RgKceYtM6GUGjfbjAnEPFhmqRmkY

mutation AddBookEvent($input: BookEventAddInput!) {
  addBookEvent(input: $input) {
    id
    user_id
    event_id
  }
}

{
  "input": {
    "event_id": 6,
    "user_id": 27
  }
}

### Query to delete booking of an event 
POST http://localhost:3000/
Content-Type: application/json
X-REQUEST-TYPE: GraphQL
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzMsImVtYWlsIjoic29meWFublRlc3RGYXZvcml0ZUBvY2xvY2suaW8iLCJmaXJzdG5hbWUiOiJTb2Z5YW5uIiwibGFzdG5hbWUiOiJMZSBTIiwiaWF0IjoxNjkwNTM0MjUwLCJleHAiOjE2OTMxMjYyNTB9.Ds7CTe3QTHWQ7x-RgKceYtM6GUGjfbjAnEPFhmqRmkY

mutation DeleteBookEvent($deleteBookEventId: Int!) {
  deleteBookEvent(id: $deleteBookEventId)
}

{
  "deleteBookEventId": 6
}

