# In GraphQL the mandatory type is Query
# The queries will be executed in parallele

type Query {

  # In GraphQL we can add comments with " 
  "It allows us to get the name of the app"
  # When we reclame informations we can precise the type to return,
  # and define if it is mandatory
  app: String!

  # To define if an attribute/request return a collection we use []
  events: [Event]
  event(id: Int!): Event

  sites: [Site]
  site(id: Int!): Site

  games: [Game]
  game(id: Int!): Game

  user: User
  login(email: String!, password: String!): JsonWebToken
 
}


