type User {
  id: Int!
  email: String!
  password: String!
  firstname: String
  lastname: String
  favorites: [Favorite]
}

input UserRegisterInput {
  email: String!
  password: String!
  firstname: String
  lastname: String
}

input UserUpdateInput {
  email: String
  password: String
  firstname: String
  lastname: String
}

type JsonWebToken{
  token: String!
}


