type User {
  id: Int!
  email: String!
  password: String!
  firstname: String
  lastname: String
  user_has_events: [user_has_event]
}

input UserRegisterInput {
  email: String!
  password: String!
  firstname: String
  lastname: String
}

input UserUpdateInput {
  email: String
  password: String
  firstname: String
  lastname: String
}

type JsonWebToken{
  token: String!
}


