type User_has_event {
  favorite: Boolean
  comment: String
  event: Event
}

input User_has_eventAddInput {
  favorite: Boolean
  comment: String
  user_id: Int!
  event_id: Int!
}

input User_has_eventUpdateInput {
  favorite: Boolean
  comment: String
  user_id: Int!
  event_id: Int!
}

